version: "3.9"
services:

  gouter:
    build: /app/gouter
    working_dir: /app
    volumes:
      - /data/gouter:/data:rw
      - /app/gouter:/app:ro
    environment:
      - ENV=prod
      - SECRETS_PATH=/data/secrets
      - GOOGLE_CLIENT_ID=4862407941-gli3asais585k29vjbnlvnh45sanjvme.apps.googleusercontent.com
    networks:
      - main

networks:
  main:
    name: main
    external: true
